INSERT INTO "Program" ("id", "slug", "sportId", "type", "name", "level", "duration", "materials", "intensity", "description", "status", "createdAt", "updatedAt")
VALUES
  ('program_boxing_pengenalan', 'boxing-pengenalan-footwork-stance', (SELECT "id" FROM "Sport" WHERE ("slug" = 'boxing' OR "name" = 'Boxing') LIMIT 1), 'LATIHAN', 'Boxing - Pengenalan Footwork & Stance', 'PENGENALAN', '2 minggu', 3, 'Rendah', 'Materi pengenalan stance, footwork, dan koordinasi dasar boxing.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('program_boxing_lanjutan', 'boxing-lanjutan-sparring-control', (SELECT "id" FROM "Sport" WHERE ("slug" = 'boxing' OR "name" = 'Boxing') LIMIT 1), 'LATIHAN', 'Boxing - Lanjutan Sparring Control', 'LANJUTAN', '4 minggu', 3, 'Sedang', 'Materi lanjutan untuk kontrol jarak, counter, dan sparring terarah.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('program_boxing_prestasi', 'boxing-prestasi-fight-plan', (SELECT "id" FROM "Sport" WHERE ("slug" = 'boxing' OR "name" = 'Boxing') LIMIT 1), 'LATIHAN', 'Boxing - Prestasi Fight Plan', 'PRESTASI', '5 minggu', 3, 'Tinggi', 'Materi prestasi untuk strategi ronde, pacing, dan evaluasi fight plan.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('program_futsal_pengenalan', 'futsal-pengenalan-ball-mastery', (SELECT "id" FROM "Sport" WHERE ("slug" = 'futsal' OR "name" = 'Futsal') LIMIT 1), 'LATIHAN', 'Futsal - Pengenalan Ball Mastery', 'PENGENALAN', '2 minggu', 3, 'Rendah', 'Materi pengenalan kontrol bola, passing dasar, dan gerak tanpa bola.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('program_futsal_lanjutan', 'futsal-lanjutan-pressing-rotasi', (SELECT "id" FROM "Sport" WHERE ("slug" = 'futsal' OR "name" = 'Futsal') LIMIT 1), 'LATIHAN', 'Futsal - Lanjutan Pressing & Rotasi', 'LANJUTAN', '4 minggu', 3, 'Sedang', 'Materi lanjutan rotasi, pressing, dan transisi cepat futsal.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('program_futsal_prestasi', 'futsal-prestasi-game-model', (SELECT "id" FROM "Sport" WHERE ("slug" = 'futsal' OR "name" = 'Futsal') LIMIT 1), 'LATIHAN', 'Futsal - Prestasi Game Model', 'PRESTASI', '5 minggu', 3, 'Tinggi', 'Materi prestasi untuk game model, set piece, dan simulasi pertandingan.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('program_bola_pengenalan', 'bola-pengenalan-basic-ball', (SELECT "id" FROM "Sport" WHERE ("slug" = 'bola' OR "name" = 'Bola') LIMIT 1), 'LATIHAN', 'Bola - Pengenalan Basic Ball', 'PENGENALAN', '2 minggu', 3, 'Rendah', 'Materi pengenalan first touch, dribble dasar, dan passing pendek.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('program_bola_lanjutan', 'bola-lanjutan-positional-play', (SELECT "id" FROM "Sport" WHERE ("slug" = 'bola' OR "name" = 'Bola') LIMIT 1), 'LATIHAN', 'Bola - Lanjutan Positional Play', 'LANJUTAN', '4 minggu', 3, 'Sedang', 'Materi lanjutan positioning, kombinasi, dan transisi permainan.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('program_bola_prestasi', 'bola-prestasi-match-performance', (SELECT "id" FROM "Sport" WHERE ("slug" = 'bola' OR "name" = 'Bola') LIMIT 1), 'LATIHAN', 'Bola - Prestasi Match Performance', 'PRESTASI', '5 minggu', 3, 'Tinggi', 'Materi prestasi untuk match performance, pressing trigger, dan evaluasi taktik.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "ProgramMaterial" ("id", "programId", "day", "material", "set", "reps", "duration", "note", "order", "createdAt", "updatedAt")
VALUES
  ('material_boxing_pengenalan_1', 'program_boxing_pengenalan', 'Hari 1', 'Stance dan guard dasar', '3 set', '10 repetisi', '40 menit', 'Fokus posisi kaki dan tangan', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_boxing_pengenalan_2', 'program_boxing_pengenalan', 'Hari 2', 'Footwork maju mundur', '3 set', '10 repetisi', '40 menit', 'Fokus keseimbangan', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_boxing_pengenalan_3', 'program_boxing_pengenalan', 'Hari 3', 'Jab dasar dan recovery guard', '3 set', '10 repetisi', '45 menit', 'Fokus teknik pukulan lurus', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_boxing_lanjutan_1', 'program_boxing_lanjutan', 'Hari 1', 'Kontrol jarak dan angle', '4 set', '8 repetisi', '55 menit', 'Fokus membaca lawan', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_boxing_lanjutan_2', 'program_boxing_lanjutan', 'Hari 2', 'Counter setelah slip', '4 set', '8 repetisi', '55 menit', 'Fokus timing counter', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_boxing_lanjutan_3', 'program_boxing_lanjutan', 'Hari 3', 'Sparring teknis terarah', '4 set', 'Simulasi', '60 menit', 'Fokus kontrol intensitas', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_boxing_prestasi_1', 'program_boxing_prestasi', 'Hari 1', 'Fight plan per ronde', '5 set', 'Simulasi', '60 menit', 'Fokus strategi', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_boxing_prestasi_2', 'program_boxing_prestasi', 'Hari 2', 'Pacing dan recovery ronde', '5 set', 'Simulasi', '60 menit', 'Fokus daya tahan', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_boxing_prestasi_3', 'program_boxing_prestasi', 'Hari 3', 'Evaluasi video sparring', '3 sesi', 'Analisis', '45 menit', 'Fokus koreksi taktik', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_pengenalan_1', 'program_futsal_pengenalan', 'Hari 1', 'Ball mastery dasar', '3 set', '10 repetisi', '40 menit', 'Fokus sentuhan bola', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_pengenalan_2', 'program_futsal_pengenalan', 'Hari 2', 'Passing pendek berpasangan', '3 set', '10 repetisi', '40 menit', 'Fokus akurasi', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_pengenalan_3', 'program_futsal_pengenalan', 'Hari 3', 'Gerak tanpa bola', '3 set', '10 repetisi', '45 menit', 'Fokus membuka ruang', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_lanjutan_1', 'program_futsal_lanjutan', 'Hari 1', 'Rotasi 3-1', '4 set', 'Simulasi', '55 menit', 'Fokus struktur tim', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_lanjutan_2', 'program_futsal_lanjutan', 'Hari 2', 'Pressing setelah kehilangan bola', '4 set', 'Simulasi', '55 menit', 'Fokus transisi', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_lanjutan_3', 'program_futsal_lanjutan', 'Hari 3', 'Transisi cepat ke finishing', '4 set', 'Simulasi', '60 menit', 'Fokus pengambilan keputusan', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_prestasi_1', 'program_futsal_prestasi', 'Hari 1', 'Game model tim', '5 set', 'Simulasi', '60 menit', 'Fokus pola utama', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_prestasi_2', 'program_futsal_prestasi', 'Hari 2', 'Set piece corner dan kick-in', '5 set', 'Simulasi', '60 menit', 'Fokus eksekusi', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_futsal_prestasi_3', 'program_futsal_prestasi', 'Hari 3', 'Simulasi pertandingan penuh', '2 babak', 'Simulasi', '70 menit', 'Fokus kesiapan laga', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_pengenalan_1', 'program_bola_pengenalan', 'Hari 1', 'First touch dasar', '3 set', '10 repetisi', '40 menit', 'Fokus kontrol bola pertama', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_pengenalan_2', 'program_bola_pengenalan', 'Hari 2', 'Dribble dasar dan perubahan arah', '3 set', '10 repetisi', '40 menit', 'Fokus koordinasi', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_pengenalan_3', 'program_bola_pengenalan', 'Hari 3', 'Passing pendek dan kontrol', '3 set', '10 repetisi', '45 menit', 'Fokus teknik dasar', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_lanjutan_1', 'program_bola_lanjutan', 'Hari 1', 'Positional play 4 zona', '4 set', 'Simulasi', '55 menit', 'Fokus posisi', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_lanjutan_2', 'program_bola_lanjutan', 'Hari 2', 'Kombinasi third-man run', '4 set', 'Simulasi', '55 menit', 'Fokus timing lari', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_lanjutan_3', 'program_bola_lanjutan', 'Hari 3', 'Transisi menyerang bertahan', '4 set', 'Simulasi', '60 menit', 'Fokus respons tim', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_prestasi_1', 'program_bola_prestasi', 'Hari 1', 'Pressing trigger', '5 set', 'Simulasi', '60 menit', 'Fokus trigger pressing', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_prestasi_2', 'program_bola_prestasi', 'Hari 2', 'Finishing dalam tekanan', '5 set', '10 repetisi', '60 menit', 'Fokus kualitas keputusan', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('material_bola_prestasi_3', 'program_bola_prestasi', 'Hari 3', 'Evaluasi taktik match performance', '3 sesi', 'Analisis', '45 menit', 'Fokus koreksi performa', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
